build:	Knapsack.java

	javac Knapsack.java


run:	Knapsack.class		

	java Knapsack


Knapsack.class:	Knapsack.java

			make build

build_python: Knapsack.py

	echo "Nothing to compile."

run_python: Knapsack.py

	python3 Knapsack.py