build:	WeightedIntervalScheduling.java

	javac WeightedIntervalScheduling.java


run:	WeightedIntervalScheduling.class		

	java WeightedIntervalScheduling


WeightedIntervalScheduling.class:	WeightedIntervalScheduling.java

			make build
