build:	MaximumMatching.java NetworkFlow.java

	javac MaximumMatching.java 
	javac NetworkFlow.java


run:	MaximumMatching.class NetworkFlow.class

	java MaximumMatching


MaximumMatching.class:	MaximumMatching.java

			make build
			
NetworkFlow.class:	NetworkFlow.java

			make build			
